# SPDX-License-Identifier: AGPL-3.0-only
"""Generate an async FastAPI app that talks SQL without Django."""

from __future__ import annotations

from typing import Any

SQL_ENGINES = ("tortoise", "sqlalchemy", "psycopg")
DEFAULT_SQL_ENGINE = "tortoise"
SQL_ENGINE_LABELS = {
    "tortoise": "Tortoise ORM (recommended — closest to Django)",
    "sqlalchemy": "SQLAlchemy 2.0 async",
    "psycopg": "psycopg3 async (PostgreSQL only)",
}


def resolve_sql_engine(value: str | None) -> str:
    engine = (value or DEFAULT_SQL_ENGINE).strip().lower()
    if engine not in SQL_ENGINES:
        raise ValueError(f"unknown SQL engine: {engine}; choose {', '.join(SQL_ENGINES)}")
    return engine


def render_async_sql_files(
    output_write: Any,
    *,
    entrypoint: str,
    manifest: dict[str, Any],
    sql_engine: str,
) -> list[str]:
    """Write store/runtime/models. Returns generated Python file names."""
    del entrypoint
    if sql_engine not in SQL_ENGINES:
        raise ValueError(f"unknown SQL engine: {sql_engine}")
    vendor = str((manifest.get("database") or {}).get("vendor") or "")
    if sql_engine == "psycopg" and vendor != "postgresql":
        raise ValueError(
            "psycopg requires PostgreSQL; this project's database is " + (vendor or "unknown")
        )
    names = ["sanka_native.py", "sanka_store.py"]
    output_write("sanka_store.py", _render_store(sql_engine))
    if sql_engine != "psycopg":
        output_write("models.py", _render_models(sql_engine, manifest))
        names.append("models.py")
    output_write("sanka_native.py", _RUNTIME)
    output_write("requirements.txt", _render_requirements(sql_engine, vendor))
    return names


def _ident(value: str) -> str:
    import re

    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_")
    return slug or "Item"


def _models_spec(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    specs: dict[str, dict[str, Any]] = {}
    for resource in manifest.get("resources", []):
        _add_model_spec(specs, resource)
        for field in resource.get("fields", []):
            if field.get("kind") != "nested_many" or not field.get("child"):
                continue
            child = field["child"]
            _add_model_spec(specs, child)
            fk = str(field.get("attname") or "")
            table = str(child.get("db_table") or "")
            if fk and table in specs:
                specs[table]["columns"].setdefault(
                    fk,
                    {
                        "name": fk,
                        "kind": "integer",
                        "pk": False,
                        "max_length": None,
                        "allow_null": False,
                        "has_default": False,
                        "default": None,
                    },
                )
    return [specs[key] for key in sorted(specs)]


def _add_model_spec(specs: dict[str, dict[str, Any]], item: dict[str, Any]) -> None:
    table = str(item.get("db_table") or "")
    if not table:
        return
    class_name = _ident(str(item.get("model_class") or item.get("object_name") or table))
    columns: dict[str, dict[str, Any]] = dict(specs.get(table, {}).get("columns") or {})
    pk = str(item.get("pk_attname") or "id")
    columns.setdefault(pk, {"name": pk, "kind": "integer", "pk": True, "max_length": None})
    for field in item.get("fields", []):
        if field.get("kind") == "nested_many":
            continue
        name = str(field.get("attname") or field["name"])
        columns[name] = {
            "name": name,
            "kind": field.get("kind") or "char",
            "pk": name == pk,
            "max_length": field.get("max_length"),
            "decimal_places": field.get("decimal_places"),
            "max_digits": field.get("max_digits"),
            "allow_null": bool(field.get("allow_null")),
            "has_default": bool(field.get("has_default")),
            "default": field.get("default"),
        }
    specs[table] = {
        "table": table,
        "class_name": class_name,
        "pk": pk,
        "ordering": list(item.get("ordering") or (pk,)),
        "columns": columns,
    }


def _render_models(sql_engine: str, manifest: dict[str, Any]) -> str:
    specs = _models_spec(manifest)
    if sql_engine == "tortoise":
        lines = [
            "# Generated by Sanka. Tortoise models mapped onto the existing Django tables.",
            "from tortoise import fields",
            "from tortoise.models import Model",
            "",
        ]
        for spec in specs:
            lines.append(f"class {spec['class_name']}(Model):")
            for column in spec["columns"].values():
                lines.append(f"    {column['name']} = {_tortoise_field(column)}")
            lines.append("    class Meta:")
            lines.append(f"        table = {spec['table']!r}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"
    lines = [
        "# Generated by Sanka. SQLAlchemy models mapped onto the existing Django tables.",
        "from sqlalchemy import Integer, Numeric, String",
        "from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column",
        "",
        "class Base(DeclarativeBase):",
        "    pass",
        "",
    ]
    for spec in specs:
        lines.append(f"class {spec['class_name']}(Base):")
        lines.append(f"    __tablename__ = {spec['table']!r}")
        for column in spec["columns"].values():
            lines.append(f"    {column['name']}: Mapped[object] = {_sqlalchemy_column(column)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _tortoise_field(column: dict[str, Any]) -> str:
    if column.get("pk"):
        return "fields.IntField(primary_key=True)"
    kind = column["kind"]
    args: list[str] = []
    if column.get("allow_null"):
        args.append("null=True")
    if kind == "char" and column.get("has_default"):
        args.append(f"default={column.get('default')!r}")
    elif kind == "char":
        args.append('default=""')
    elif column.get("has_default") and column.get("default") is not None:
        args.append(f"default={column['default']!r}")
    extra = (", " + ", ".join(args)) if args else ""
    if kind in {"integer", "related_pk"}:
        wrapped = f"({extra.strip(', ')})" if extra else "()"
        return f"fields.IntField{wrapped}"
    if kind == "decimal":
        digits = int(column.get("max_digits") or 12)
        places = int(column.get("decimal_places") or 2)
        return f"fields.DecimalField(max_digits={digits}, decimal_places={places}{extra})"
    max_length = int(column.get("max_length") or 255)
    return f"fields.CharField(max_length={max_length}{extra})"


def _sqlalchemy_column(column: dict[str, Any]) -> str:
    if column.get("pk"):
        return "mapped_column(Integer, primary_key=True)"
    kind = column["kind"]
    nullable = "nullable=True" if column.get("allow_null") else "nullable=False"
    if kind in {"integer", "related_pk"}:
        return f"mapped_column(Integer, {nullable})"
    if kind == "decimal":
        digits = int(column.get("max_digits") or 12)
        places = int(column.get("decimal_places") or 2)
        return f"mapped_column(Numeric({digits}, {places}), {nullable})"
    max_length = int(column.get("max_length") or 255)
    return f"mapped_column(String({max_length}), {nullable})"


def _render_requirements(sql_engine: str, vendor: str) -> str:
    lines = ["fastapi>=0.115,<1", "uvicorn[standard]>=0.30,<1"]
    if sql_engine == "tortoise":
        lines.append("tortoise-orm>=0.21,<1")
        lines.append("asyncpg>=0.29,<1" if vendor == "postgresql" else "aiosqlite>=0.20,<1")
    elif sql_engine == "sqlalchemy":
        lines.append("sqlalchemy>=2.0,<3")
        lines.append("asyncpg>=0.29,<1" if vendor == "postgresql" else "aiosqlite>=0.20,<1")
    else:
        lines.append("psycopg[binary]>=3.2,<4")
    return "\n".join(lines) + "\n"


def _render_store(sql_engine: str) -> str:
    if sql_engine == "tortoise":
        return _TORTOISE_STORE
    if sql_engine == "sqlalchemy":
        return _SQLALCHEMY_STORE
    return _PSYCOPG_STORE


_URL_HELPER = """
from pathlib import Path
import json
import os

HERE = Path(__file__).resolve().parent


def database_url() -> str:
    env = os.environ.get("SANKA_DATABASE_URL") or os.environ.get("SANKA_TEST_DB")
    captured = json.loads((HERE / "sanka-manifest.json").read_text(encoding="utf-8"))
    database = captured.get("database") or {}
    vendor = str(database.get("vendor") or "sqlite")
    if env and "://" in env:
        return env
    if env and vendor == "sqlite":
        return _sqlite_url(env)
    name = str(database.get("name") or "")
    if vendor == "postgresql":
        raise RuntimeError(
            "set SANKA_DATABASE_URL for PostgreSQL (password is not stored in the scan)"
        )
    path = Path(name)
    if not path.is_absolute():
        path = (HERE / captured.get("source_root", ".")).resolve() / name
    return _sqlite_url(str(path))
"""


_TORTOISE_STORE = (
    """# Generated by Sanka. Async store over Tortoise ORM (existing Django tables).
from __future__ import annotations

from typing import Any

from tortoise import Tortoise

"""
    + _URL_HELPER
    + """

def _sqlite_url(path: str) -> str:
    return "sqlite:///" + str(Path(path).resolve())


async def init_db() -> None:
    await Tortoise.init(db_url=database_url(), modules={"models": ["models"]})


async def close_db() -> None:
    await Tortoise.close_connections()


def _cls(resource: dict[str, Any]) -> Any:
    import models as models_mod

    return getattr(models_mod, str(resource["model_class"]))


def _pk(resource: dict[str, Any]) -> str:
    return str(resource.get("pk_attname") or "id")


def _coerce_pk(raw: Any) -> tuple[Any, str]:
    try:
        return int(str(raw)), ""
    except (TypeError, ValueError):
        return None, "invalid"


async def fetch_all(resource: dict[str, Any]) -> list[Any]:
    query = _cls(resource).all()
    ordering = list(resource.get("ordering") or ())
    if ordering:
        query = query.order_by(*ordering)
    return await query


async def fetch_one(resource: dict[str, Any], raw: Any) -> tuple[Any, str]:
    pk, error = _coerce_pk(raw)
    if error:
        return None, error
    row = await _cls(resource).get_or_none(**{_pk(resource): pk})
    return (row, "") if row is not None else (None, "missing")


async def create_row(resource: dict[str, Any], data: dict[str, Any]) -> Any:
    return await _cls(resource).create(**data)


async def save_row(_resource: dict[str, Any], instance: Any) -> None:
    await instance.save()


async def delete_row(_resource: dict[str, Any], instance: Any) -> None:
    await instance.delete()


async def unique_taken(
    resource: dict[str, Any], field: str, value: Any, exclude_pk: Any = None
) -> bool:
    query = _cls(resource).filter(**{field: value})
    if exclude_pk is not None:
        query = query.exclude(**{_pk(resource): exclude_pk})
    return await query.exists()


async def fetch_children(spec: dict[str, Any], parent_id: Any) -> list[Any]:
    child = spec["child"]
    fk = spec.get("attname") or spec["name"]
    query = _cls(child).filter(**{fk: parent_id})
    ordering = list(child.get("ordering") or ())
    if ordering:
        query = query.order_by(*ordering)
    return await query


def _placeholder() -> str:
    return "?" if database_url().startswith("sqlite") else "$1"


async def token_user_id(auth: dict[str, Any], key: str) -> Any:
    conn = Tortoise.get_connection("default")
    mark = _placeholder()
    sql = (
        f'SELECT "{auth["token_user_column"]}" AS user_id '
        f'FROM "{auth["token_db_table"]}" WHERE "{auth["token_key_column"]}" = {mark}'
    )
    _, rows = await conn.execute_query(sql, [key])
    if not rows:
        return None
    return rows[0][0]


async def user_is_active(user_id: Any) -> bool | None:
    conn = Tortoise.get_connection("default")
    mark = _placeholder()
    _, rows = await conn.execute_query(
        f'SELECT "is_active" FROM "auth_user" WHERE "id" = {mark}', [user_id]
    )
    if not rows:
        return None
    return bool(rows[0][0])
"""
)


_SQLALCHEMY_STORE = (
    """# Generated by Sanka. Async store over SQLAlchemy (existing Django tables).
from __future__ import annotations

from typing import Any

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

"""
    + _URL_HELPER
    + """

def _sqlite_url(path: str) -> str:
    return "sqlite+aiosqlite:///" + str(Path(path).resolve())


_ENGINE = None
_SESSION = None


def _sessionmaker() -> async_sessionmaker[AsyncSession]:
    global _ENGINE, _SESSION
    if _SESSION is None:
        url = database_url()
        if url.startswith("postgresql://"):
            url = url.replace("postgresql://", "postgresql+asyncpg://", 1)
        elif url.startswith("postgres://"):
            url = url.replace("postgres://", "postgresql+asyncpg://", 1)
        _ENGINE = create_async_engine(url)
        _SESSION = async_sessionmaker(_ENGINE, expire_on_commit=False)
    return _SESSION


async def init_db() -> None:
    _sessionmaker()


async def close_db() -> None:
    global _ENGINE, _SESSION
    if _ENGINE is not None:
        await _ENGINE.dispose()
    _ENGINE = None
    _SESSION = None


def _cls(resource: dict[str, Any]) -> Any:
    import models as models_mod

    return getattr(models_mod, str(resource["model_class"]))


def _pk(resource: dict[str, Any]) -> str:
    return str(resource.get("pk_attname") or "id")


def _coerce_pk(raw: Any) -> tuple[Any, str]:
    try:
        return int(str(raw)), ""
    except (TypeError, ValueError):
        return None, "invalid"


async def fetch_all(resource: dict[str, Any]) -> list[Any]:
    model = _cls(resource)
    stmt = select(model)
    for name in resource.get("ordering") or ():
        stmt = stmt.order_by(getattr(model, name))
    async with _sessionmaker()() as session:
        return list((await session.scalars(stmt)).all())


async def fetch_one(resource: dict[str, Any], raw: Any) -> tuple[Any, str]:
    pk, error = _coerce_pk(raw)
    if error:
        return None, error
    model = _cls(resource)
    stmt = select(model).where(getattr(model, _pk(resource)) == pk)
    async with _sessionmaker()() as session:
        row = await session.scalar(stmt)
    return (row, "") if row is not None else (None, "missing")


async def create_row(resource: dict[str, Any], data: dict[str, Any]) -> Any:
    model = _cls(resource)
    row = model(**data)
    async with _sessionmaker()() as session:
        session.add(row)
        await session.commit()
        await session.refresh(row)
    return row


async def save_row(_resource: dict[str, Any], instance: Any) -> None:
    async with _sessionmaker()() as session:
        merged = await session.merge(instance)
        await session.commit()
        await session.refresh(merged)
        for key, value in vars(merged).items():
            if not key.startswith("_"):
                setattr(instance, key, value)


async def delete_row(_resource: dict[str, Any], instance: Any) -> None:
    async with _sessionmaker()() as session:
        merged = await session.merge(instance)
        await session.delete(merged)
        await session.commit()


async def unique_taken(
    resource: dict[str, Any], field: str, value: Any, exclude_pk: Any = None
) -> bool:
    model = _cls(resource)
    stmt = select(model).where(getattr(model, field) == value)
    if exclude_pk is not None:
        stmt = stmt.where(getattr(model, _pk(resource)) != exclude_pk)
    async with _sessionmaker()() as session:
        row = await session.scalar(stmt)
    return row is not None


async def fetch_children(spec: dict[str, Any], parent_id: Any) -> list[Any]:
    child = spec["child"]
    model = _cls(child)
    fk = spec.get("attname") or spec["name"]
    stmt = select(model).where(getattr(model, fk) == parent_id)
    for name in child.get("ordering") or ():
        stmt = stmt.order_by(getattr(model, name))
    async with _sessionmaker()() as session:
        return list((await session.scalars(stmt)).all())


async def token_user_id(auth: dict[str, Any], key: str) -> Any:
    sql = text(
        f'SELECT "{auth["token_user_column"]}" FROM "{auth["token_db_table"]}" '
        f'WHERE "{auth["token_key_column"]}" = :key'
    )
    async with _sessionmaker()() as session:
        result = await session.execute(sql, {"key": key})
        row = result.first()
    return None if row is None else row[0]


async def user_is_active(user_id: Any) -> bool | None:
    sql = text('SELECT "is_active" FROM "auth_user" WHERE "id" = :id')
    async with _sessionmaker()() as session:
        result = await session.execute(sql, {"id": user_id})
        row = result.first()
    if row is None:
        return None
    return bool(row[0])
"""
)


_PSYCOPG_STORE = (
    """# Generated by Sanka. Async store over psycopg3 (existing Django tables).
from __future__ import annotations

from typing import Any

import psycopg
from psycopg.rows import dict_row

"""
    + _URL_HELPER
    + """

def _sqlite_url(path: str) -> str:
    raise RuntimeError("psycopg does not support SQLite")


_CONNINFO = ""


async def init_db() -> None:
    global _CONNINFO
    _CONNINFO = os.environ.get("SANKA_DATABASE_URL") or ""
    if not _CONNINFO:
        raise RuntimeError("set SANKA_DATABASE_URL")


async def close_db() -> None:
    return None


def _pk(resource: dict[str, Any]) -> str:
    return str(resource.get("pk_attname") or "id")


def _table(resource: dict[str, Any]) -> str:
    return str(resource["db_table"])


def _coerce_pk(raw: Any) -> tuple[Any, str]:
    try:
        return int(str(raw)), ""
    except (TypeError, ValueError):
        return None, "invalid"


def _row(resource: dict[str, Any], data: dict[str, Any]) -> dict[str, Any]:
    return data


async def fetch_all(resource: dict[str, Any]) -> list[Any]:
    order = ", ".join(f'"{name}"' for name in (resource.get("ordering") or ("id",)))
    sql = f'SELECT * FROM "{_table(resource)}" ORDER BY {order}'
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor(row_factory=dict_row) as cur:
            await cur.execute(sql)
            return list(await cur.fetchall())


async def fetch_one(resource: dict[str, Any], raw: Any) -> tuple[Any, str]:
    pk, error = _coerce_pk(raw)
    if error:
        return None, error
    sql = f'SELECT * FROM "{_table(resource)}" WHERE "{_pk(resource)}" = %s'
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor(row_factory=dict_row) as cur:
            await cur.execute(sql, (pk,))
            row = await cur.fetchone()
    return (row, "") if row is not None else (None, "missing")


async def create_row(resource: dict[str, Any], data: dict[str, Any]) -> Any:
    cols = ", ".join(f'"{key}"' for key in data)
    placeholders = ", ".join(["%s"] * len(data))
    sql = (
        f'INSERT INTO "{_table(resource)}" ({cols}) VALUES ({placeholders}) RETURNING *'
    )
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor(row_factory=dict_row) as cur:
            await cur.execute(sql, tuple(data.values()))
            row = await cur.fetchone()
        await conn.commit()
    return row


async def save_row(resource: dict[str, Any], instance: Any) -> None:
    pk = _pk(resource)
    data = {key: value for key, value in dict(instance).items() if key != pk}
    assignments = ", ".join(f'"{key}" = %s' for key in data)
    sql = f'UPDATE "{_table(resource)}" SET {assignments} WHERE "{pk}" = %s'
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor() as cur:
            await cur.execute(sql, (*data.values(), instance[pk]))
        await conn.commit()


async def delete_row(resource: dict[str, Any], instance: Any) -> None:
    pk = _pk(resource)
    sql = f'DELETE FROM "{_table(resource)}" WHERE "{pk}" = %s'
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor() as cur:
            await cur.execute(sql, (instance[pk],))
        await conn.commit()


async def unique_taken(
    resource: dict[str, Any], field: str, value: Any, exclude_pk: Any = None
) -> bool:
    sql = f'SELECT 1 FROM "{_table(resource)}" WHERE "{field}" = %s'
    params: list[Any] = [value]
    if exclude_pk is not None:
        sql += f' AND "{_pk(resource)}" <> %s'
        params.append(exclude_pk)
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor() as cur:
            await cur.execute(sql, params)
            return await cur.fetchone() is not None


async def fetch_children(spec: dict[str, Any], parent_id: Any) -> list[Any]:
    child = spec["child"]
    fk = spec.get("attname") or spec["name"]
    order = ", ".join(f'"{name}"' for name in (child.get("ordering") or ("id",)))
    sql = f'SELECT * FROM "{child["db_table"]}" WHERE "{fk}" = %s ORDER BY {order}'
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor(row_factory=dict_row) as cur:
            await cur.execute(sql, (parent_id,))
            return list(await cur.fetchall())


async def token_user_id(auth: dict[str, Any], key: str) -> Any:
    sql = (
        f'SELECT "{auth["token_user_column"]}" FROM "{auth["token_db_table"]}" '
        f'WHERE "{auth["token_key_column"]}" = %s'
    )
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor() as cur:
            await cur.execute(sql, (key,))
            row = await cur.fetchone()
    return None if row is None else row[0]


async def user_is_active(user_id: Any) -> bool | None:
    async with await psycopg.AsyncConnection.connect(_CONNINFO) as conn:
        async with conn.cursor() as cur:
            await cur.execute('SELECT "is_active" FROM "auth_user" WHERE "id" = %s', (user_id,))
            row = await cur.fetchone()
    if row is None:
        return None
    return bool(row[0])
"""
)


_RUNTIME = r'''# Generated by Sanka under the license selected for this generated application.
"""Async FastAPI request layer. Validation is a native reimplementation of the
captured DRF serializer semantics. Persistence is async SQL via sanka_store —
Django is not imported.
"""
from __future__ import annotations

import json
import re
from decimal import Decimal, InvalidOperation
from typing import Any

from fastapi import Request
from fastapi.responses import JSONResponse, Response

import sanka_store as store

HERE_MANIFEST = __import__("pathlib").Path(__file__).resolve().parent
MANIFEST = json.loads((HERE_MANIFEST / "sanka-manifest.json").read_text(encoding="utf-8"))

_DECIMAL_TAIL = re.compile(r"\.0*\s*$")
_MAX_STRING_LENGTH = 1000


def _attr(instance: Any, name: str) -> Any:
    if isinstance(instance, dict):
        return instance.get(name)
    return getattr(instance, name)


def _instance_pk(instance: Any) -> Any:
    if isinstance(instance, dict):
        return instance.get("id")
    return getattr(instance, "pk", None) or getattr(instance, "id")


def _set_attr(instance: Any, name: str, value: Any) -> None:
    if isinstance(instance, dict):
        instance[name] = value
    else:
        setattr(instance, name, value)


def resource(view: str) -> dict[str, Any]:
    for item in MANIFEST["resources"]:
        if item["view"] == view:
            return item
    raise KeyError(view)


async def read_raw_body(request: Request) -> bytes:
    return await request.body()


def _represent(spec: dict[str, Any], value: Any) -> Any:
    if spec["kind"] == "decimal" and value is not None:
        places = spec.get("decimal_places") or 0
        quantum = Decimal(1).scaleb(-places)
        return str(Decimal(value).quantize(quantum))
    return value


async def _serialize_fields(fields: list[dict[str, Any]], instance: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {}
    for spec in fields:
        if spec["kind"] == "nested_many":
            child = spec["child"]
            related = await store.fetch_children(spec, _instance_pk(instance))
            payload[spec["name"]] = [
                await _serialize_fields(child["fields"], row) for row in related
            ]
        else:
            raw = _attr(instance, spec.get("attname") or spec["name"])
            payload[spec["name"]] = _represent(spec, raw)
    return payload


async def _serialize(resource: dict[str, Any], instance: Any) -> dict[str, Any]:
    return await _serialize_fields(resource["fields"], instance)


def _clean_integer(spec: dict[str, Any], value: Any) -> tuple[Any, list[str]]:
    messages = spec["messages"]
    if isinstance(value, str) and len(value) > _MAX_STRING_LENGTH:
        return None, [messages["max_string_length"]]
    try:
        cleaned = int(_DECIMAL_TAIL.sub("", str(value).strip()))
    except (TypeError, ValueError):
        return None, [messages["invalid"]]
    errors = []
    if spec.get("min_value") is not None and cleaned < spec["min_value"]:
        errors.append(messages["min_value"])
    if spec.get("max_value") is not None and cleaned > spec["max_value"]:
        errors.append(messages["max_value"])
    return cleaned, errors


def _clean_char(spec: dict[str, Any], value: Any) -> tuple[Any, list[str]]:
    messages = spec["messages"]
    if value == "" or (spec["trim_whitespace"] and isinstance(value, str) and not value.strip()):
        if spec["allow_blank"]:
            return "", []
        return None, [messages["blank"]]
    if isinstance(value, bool) or not isinstance(value, (str, int, float)):
        return None, [messages["invalid"]]
    cleaned = str(value)
    if spec["trim_whitespace"]:
        cleaned = cleaned.strip()
    errors = []
    if spec.get("max_length") is not None and len(cleaned) > spec["max_length"]:
        errors.append(messages["max_length"])
    if spec.get("min_length") is not None and len(cleaned) < spec["min_length"]:
        errors.append(messages["min_length"])
    if "\x00" in cleaned and messages.get("null_characters"):
        errors.append(messages["null_characters"])
    if messages.get("surrogate_characters") and any(
        0xD800 <= ord(char) <= 0xDFFF for char in cleaned
    ):
        errors.append(messages["surrogate_characters"])
    return cleaned, errors


def _clean_decimal(spec: dict[str, Any], value: Any) -> tuple[Any, list[str]]:
    messages = spec["messages"]
    if isinstance(value, bool):
        return None, [messages["invalid"]]
    if isinstance(value, str) and len(value) > _MAX_STRING_LENGTH:
        return None, [messages["max_string_length"]]
    try:
        cleaned = Decimal(str(value).strip())
    except (InvalidOperation, ValueError, TypeError):
        return None, [messages["invalid"]]
    if cleaned.is_nan() or cleaned.is_infinite():
        return None, [messages["invalid"]]
    _sign, digittuple, exponent = cleaned.as_tuple()
    if not isinstance(exponent, int):
        return None, [messages["invalid"]]
    if exponent >= 0:
        digits = len(digittuple) + exponent
        decimals = 0
    elif abs(exponent) > len(digittuple):
        digits = decimals = abs(exponent)
    else:
        digits = len(digittuple)
        decimals = abs(exponent)
    whole_digits = digits - decimals
    max_digits = spec.get("max_digits")
    decimal_places = spec.get("decimal_places")
    if max_digits is not None and digits > max_digits:
        return None, [messages["max_digits"]]
    if decimal_places is not None and decimals > decimal_places:
        return None, [messages["max_decimal_places"]]
    if (
        max_digits is not None
        and decimal_places is not None
        and whole_digits > (max_digits - decimal_places)
    ):
        return None, [messages["max_whole_digits"]]
    return cleaned, []


def _clean_choice(spec: dict[str, Any], value: Any) -> tuple[Any, list[str]]:
    messages = spec["messages"]
    if value in spec["choices"]:
        return value, []
    return None, [messages["invalid_choice"].format(input=value)]


def _validate_scalar_fields(
    fields: list[dict[str, Any]], payload: Any, *, partial: bool
) -> tuple[dict[str, Any], dict[str, Any]]:
    if not isinstance(payload, dict):
        kind = type(payload).__name__
        return {}, {
            "non_field_errors": [
                "Invalid data. Expected a dictionary, but got {0}.".format(kind)
            ]
        }
    validated: dict[str, Any] = {}
    errors: dict[str, Any] = {}
    for spec in fields:
        if spec["kind"] == "nested_many" or spec.get("read_only"):
            continue
        name = spec["name"]
        if name not in payload:
            if spec["required"] and not partial:
                errors[name] = [spec["messages"]["required"]]
            elif spec.get("has_default") and not partial:
                validated[spec.get("attname") or name] = spec["default"]
            continue
        raw = payload[name]
        if raw is None:
            if spec["allow_null"]:
                validated[spec.get("attname") or name] = None
            else:
                errors[name] = [spec["messages"]["null"]]
            continue
        cleaner = {
            "integer": _clean_integer,
            "char": _clean_char,
            "decimal": _clean_decimal,
            "choice": _clean_choice,
            "related_pk": _clean_integer,
        }.get(spec["kind"])
        if cleaner is None:
            errors[name] = ["This field is not supported."]
            continue
        cleaned, field_errors = cleaner(spec, raw)
        if field_errors:
            errors[name] = field_errors
        else:
            validated[spec.get("attname") or name] = cleaned
    return validated, errors


async def _validate(
    resource: dict[str, Any],
    payload: Any,
    *,
    partial: bool,
    instance: Any,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    if not isinstance(payload, dict):
        return {}, {}, {"non_field_errors": [
            "Invalid data. Expected a dictionary, but got {0}.".format(type(payload).__name__)
        ]}
    validated, errors = _validate_scalar_fields(resource["fields"], payload, partial=partial)
    nested: dict[str, Any] = {}
    for spec in resource["fields"]:
        name = spec["name"]
        if spec["kind"] != "nested_many" or spec.get("read_only"):
            continue
        if name not in payload:
            if spec["required"] and not partial:
                errors[name] = [spec["messages"]["required"]]
            continue
        raw = payload[name]
        if raw is None:
            errors[name] = [spec["messages"]["null"]]
            continue
        if not isinstance(raw, list):
            template = spec["messages"]["not_a_list"]
            errors[name] = {
                "non_field_errors": [template.format(input_type=type(raw).__name__)]
            }
            continue
        item_errors: dict[str, Any] = {}
        items: list[dict[str, Any]] = []
        for index, raw_item in enumerate(raw):
            child_validated, child_errors = _validate_scalar_fields(
                spec["child"]["fields"], raw_item, partial=False
            )
            if child_errors:
                item_errors[str(index)] = child_errors
            else:
                items.append(child_validated)
        if item_errors:
            errors[name] = item_errors
        else:
            nested[name] = items
    for spec in resource["fields"]:
        column = spec.get("attname") or spec["name"]
        if spec.get("unique") and column in validated and validated[column] is not None:
            exclude = None if instance is None else _attr(
                instance, resource.get("pk_attname") or "id"
            )
            if await store.unique_taken(resource, column, validated[column], exclude):
                errors[spec["name"]] = [spec["unique_message"]]
                validated.pop(column, None)
    return validated, nested, errors


def _parse_json(raw: bytes) -> tuple[Any, Response | None]:
    try:
        return json.loads(raw), None
    except json.JSONDecodeError as exc:
        return None, JSONResponse({"detail": f"JSON parse error - {exc}"}, status_code=400)


def _not_found(resource: dict[str, Any], allow: str, cause: str) -> Response:
    if cause == "missing":
        detail = f"No {resource['object_name']} matches the given query."
    else:
        detail = MANIFEST["generic_messages"]["not_found"]
    return JSONResponse({"detail": detail}, status_code=404, headers={"Allow": allow})


def _auth_error(message: str, auth: dict[str, Any], allow: str) -> Response:
    return JSONResponse(
        {"detail": message},
        status_code=401,
        headers={"Allow": allow, "WWW-Authenticate": auth["messages"]["www_authenticate"]},
    )


async def _authenticate(request: Request, auth: dict[str, Any], allow: str) -> tuple[Any, Any]:
    messages = auth["messages"]
    header = request.headers.get("authorization", "")
    parts = header.split()
    if not parts or parts[0].lower() != auth["token_keyword"].lower():
        return None, None
    if len(parts) == 1:
        return None, _auth_error(messages["empty_header"], auth, allow)
    if len(parts) > 2:
        return None, _auth_error(messages["spaced_header"], auth, allow)
    user_id = await store.token_user_id(auth, parts[1])
    if user_id is None:
        return None, _auth_error(messages["invalid_token"], auth, allow)
    is_active = await store.user_is_active(user_id)
    if is_active is None:
        return None, _auth_error(messages["invalid_token"], auth, allow)
    if not is_active:
        return None, _auth_error(messages["inactive_user"], auth, allow)
    return user_id, None


async def _require_user(request: Request, auth: dict[str, Any], allow: str) -> tuple[Any, Any]:
    user_id, error = await _authenticate(request, auth, allow)
    if error is not None:
        return None, error
    if user_id is None:
        return None, _auth_error(auth["messages"]["no_credentials"], auth, allow)
    return user_id, None


def _forbidden(auth: dict[str, Any], allow: str) -> Response:
    return JSONResponse(
        {"detail": auth["messages"]["forbidden"]}, status_code=403, headers={"Allow": allow}
    )


async def handle(
    spec: dict[str, Any],
    operation: str,
    request: Request,
    raw_body: bytes | None = None,
) -> Any:
    path = next(route["path"] for route in spec["routes"] if route["operation"] == operation)
    allow = MANIFEST["allow"][path]
    auth = spec.get("auth")
    user_id = None
    if auth is not None:
        user_id, gate_error = await _require_user(request, auth, allow)
        if gate_error is not None:
            return gate_error
    if operation == "list":
        rows = await store.fetch_all(spec)
        payload = [await _serialize(spec, item) for item in rows]
        return JSONResponse(payload, headers={"Allow": allow})
    if operation == "retrieve":
        instance, miss = await store.fetch_one(spec, request.path_params.get(spec["lookup"]))
        if instance is None:
            return _not_found(spec, allow, miss)
        return JSONResponse(await _serialize(spec, instance), headers={"Allow": allow})
    if operation == "destroy":
        instance, miss = await store.fetch_one(spec, request.path_params.get(spec["lookup"]))
        if instance is None:
            return _not_found(spec, allow, miss)
        if (
            auth is not None
            and auth.get("owner_attname")
            and _attr(instance, auth["owner_attname"]) != user_id
        ):
            return _forbidden(auth, allow)
        for field in spec["fields"]:
            if field["kind"] == "nested_many":
                for child in await store.fetch_children(field, _instance_pk(instance)):
                    await store.delete_row(field["child"], child)
        await store.delete_row(spec, instance)
        return Response(status_code=204, headers={"Allow": allow})
    payload, parse_error = _parse_json(raw_body or b"")
    if parse_error is not None:
        parse_error.headers["Allow"] = allow
        return parse_error
    if operation == "create":
        validated, nested, errors = await _validate(spec, payload, partial=False, instance=None)
        if errors:
            return JSONResponse(errors, status_code=400, headers={"Allow": allow})
        if auth is not None and auth.get("inject_owner_attname"):
            validated[auth["inject_owner_attname"]] = user_id
        instance = await store.create_row(spec, validated)
        for field in spec["fields"]:
            if field["kind"] == "nested_many" and field["name"] in nested:
                fk = field.get("attname") or field["name"]
                parent_id = _attr(instance, spec.get("pk_attname") or "id")
                for child in nested[field["name"]]:
                    child[fk] = parent_id
                    await store.create_row(field["child"], child)
        return JSONResponse(
            await _serialize(spec, instance), status_code=201, headers={"Allow": allow}
        )
    instance, miss = await store.fetch_one(spec, request.path_params.get(spec["lookup"]))
    if instance is None:
        return _not_found(spec, allow, miss)
    if (
        auth is not None
        and auth.get("owner_attname")
        and _attr(instance, auth["owner_attname"]) != user_id
    ):
        return _forbidden(auth, allow)
    validated, _nested, errors = await _validate(
        spec, payload, partial=(operation == "partial_update"), instance=instance
    )
    if errors:
        return JSONResponse(errors, status_code=400, headers={"Allow": allow})
    for name, value in validated.items():
        _set_attr(instance, name, value)
    await store.save_row(spec, instance)
    return JSONResponse(await _serialize(spec, instance), headers={"Allow": allow})


async def api_root(request: Request, path: str) -> Any:
    root = next(item for item in MANIFEST["api_roots"] if item["path"] == path)
    allow = MANIFEST["allow"][path]
    base = str(request.base_url).rstrip("/")
    payload = {key: f"{base}{link}" for key, link in root["links"]}
    return JSONResponse(payload, headers={"Allow": allow})
'''
